### ISSUE TITLE
Possible problems working with 2DA files

### ISSUE THREAD

**Issue by th3w1zard1** [NickHugi/PyKotor#12]
There seem to be major discrepancies in what TSLPatcher is doing with 2da files vs PyKotor. Nothing specifically looks off in Holocron Toolset but Winmerge spots dozens and dozens of bytes that differ. Here are both appearance.2da files after installing the TSLRCM Tweak Pack:

[appearance.2da_tslpatcher.zip](https://github.com/NickHugi/PyKotor/files/11994408/appearance.2da_tslpatcher.zip)
[appearance.2da_pykotor.zip](https://github.com/NickHugi/PyKotor/files/11994409/appearance.2da_pykotor.zip)

**Comment by DarthParametric** [comment]
Interestingly though when using either stoffe's Convert2DA or Xoreos Tools' convert2da, both files converted to plain text are identical.

**Comment by th3w1zard1** [comment]
i'm three hours into a playthrough, i haven't noticed any problems. I'm guessing the differing bytes are header related or something arbitrary. Closing
