### ISSUE TITLE
Holocron Toolkit: NSS editor Compile option can write to .rim files even with save to RIM disabled

### ISSUE THREAD

**Issue by JoeNotCharles** [NickHugi/PyKotor#68]
1. Make sure the "Allow saving resources to RIM files" setting is turned off.
2. Open a foo_s.rim file from an installed game.
3. Open any NCS resource in the .rim. Say it's "a_script".

The NSS editor will open with the filename set to foo_s.rim/a_script.ncs. (Either it'll have the decompiled source of a_script.ncs, or it'll be blank. Doesn't matter either way.)

4. Paste a completely new script into the editor.
5. Choose "Compile". (I used nwnnsscomp.exe, haven't tested with the internal compiler.)

The new script will be compiled to an NCS resource and saved over a_script in foo_s.rim, even though "allow saving resources to RIM files" is disabled.

**Comment by JoeNotCharles** [comment]
I almost have a fix for this, but it needs some cleanup before I commit it.

The root cause is that NSSEditor.compileCurrentScript doesn't go through the save() / build() path, instead it has custom code to write the compiiled script, which doesn't check settings.disableRIMSaving. (Also NSSEditor.build() doesn't work at all for NCS files - it looks like a "raise ValueError" was pasted into the success path by mistake.)

**Comment by th3w1zard1** [comment]
Thank you for reporting this. There's a few niche scenarios like this where the toolset isn't properly checking that setting.

**Comment by th3w1zard1** [comment]
To clarify is this happening in the beta version or the last DS release version?

**Comment by JoeNotCharles** [comment]
I tested both the beta release and the PyKotor master branch.

I have a fix at https://github.com/NickHugi/PyKotor/pull/70, but it's a bit
wonky. Not sure if it's the correct approach.

**Comment by th3w1zard1** [comment]
It's a good starting point at least. Btw the betas are created from the bleeding-edge branch

**Comment by th3w1zard1** [comment]
I'm struggling to reproduce this issue. NSS scripts are compiling fine with that option disabled. Is there any way you can attach errorlog.txt so I can see the stack trace?

**Comment by JoeNotCharles** [comment]
> I'm struggling to reproduce this issue. NSS scripts are compiling fine with that option disabled. Is there any way you can attach errorlog.txt so I can see the stack trace?
> 
> EDIT: Sorry I commented this in the wrong place. You mentioned the ValueError was being raised in the incorrect spot. I belive I meant to write this on the PR. Did that come with a stack trace?

Split that out into https://github.com/NickHugi/PyKotor/issues/71

**Comment by JoeNotCharles** [comment]
I messed up the branches and pull requests in my repo. The most up-to-date fix for this is now at https://github.com/JoeNotCharles/PyKotor/tree/fix_compile_script (which includes the commit from the PR I accidentally deleted, plus another cleanup)
