### ISSUE TITLE
Wishlist: when opening an NCS resource, let the user pick an NSS from Vanilla_KOTOR_Script_Source instead of decompiling

### ISSUE THREAD

**Issue by JoeNotCharles** [NickHugi/PyKotor#75]

**Comment by JoeNotCharles** [comment]
There's an implementation of this in https://github.com/JoeNotCharles/PyKotor/tree/load_nss_before_nsc. (It contains the commits from a PR I accidentally deleted, plus another that makes the new setting off-by-default.)

**Comment by th3w1zard1** [comment]
@JoeNotCharles With the successful merge of #90 this feature is looking like a real possibility! 90% of this code is written now.

**Comment by th3w1zard1** [comment]
Thanks for the great idea, this is now implemented on `master` :)
